FROM alpine:3.6

MAINTAINER Mikhail Chusavitin chusavitin@gmail.com

RUN apk update \
 && apk upgrade \
 && apk add --no-cache \
            rsync \
            dcron \
 && rm -rf /var/cache/apk/*

RUN mkdir -p /data/from \
 && mkdir -p /data/to

RUN mkdir -p /var/log/cron \
 && mkdir -m 0644 -p /var/spool/cron/crontabs \
 && touch /var/log/cron/cron.log \
 && mkdir -m 0644 -p /etc/cron.d

ADD https://raw.githubusercontent.com/mchus/arb/docker-version/rsync.sh /
RUN chmod +x /rsync.sh

RUN crontab -l | { cat; echo "*/3 * * * * sh /rsync.sh"; } | crontab -

VOLUME /data/from
VOLUME /data/to

CMD crond -s /var/spool/cron/crontabs -b -L /var/log/cron/cron.log "$@" && tail -f /var/log/cron/cron.log
