#!/bin/bash
curl https://raw.githubusercontent.com/mchus/arb/master/pro.mchus.arb.plist --output ~/Library/LaunchAgents/pro.mchus.arb.plist
mkdir -p ~/.backup
curl https://raw.githubusercontent.com/mchus/arb/master/rsync.sh --output ~/.backup/rsync.sh
launchctl load ~/Library/LaunchAgents/pro.mchus.arb.plist
launchctl start pro.mchus.arb
